### ISSUE TITLE
cpu速度太慢

### ISSUE THREAD

**Issue by xxlxms** [RapidAI/RapidTable#17]
这个是不是跟图片大小有关系，很多财报的表格都要8s-10s，也太慢了

**Comment by Joker1212** [comment]
财报有可能哈，可以看下耗时发生在表格结构解析还是ocr阶段，如果是ocr的话，可以使用rapid-ocr-gpu版本
https://rapidai.github.io/RapidOCRDocs/install_usage/rapidocr_paddle/usage/#_3

**Comment by xxlxms** [comment]
这个gpu里面默认用的是百度最新的模型吗

**Comment by Joker1212** [comment]
可以选择ppocrv4的模型，是ocr模型，不是表格模型，表格模型还是走cpu的，如果表格识别也需要gpu，可以直接参考readme去paddlex那里查看使用哈
