### ISSUE TITLE
pip install rapidocr_onnxruntime

### ISSUE THREAD

**Issue by lyc728** [RapidAI/RapidTable#27]
你好 表格识别默认走的是cpu推理吗

**Comment by lyc728** [comment]
你好 为什么这个无线表格很标准 表头识别有问题
<img width="284" alt="企业微信截图_17326125002358" src="https://github.com/user-attachments/assets/c3c9536b-f69d-484f-809e-848380005c0f">
html结果如下：
`'<html><body><table><tr><td colspan="6">人民币百万元 2022 2023 2024E</td></tr><tr><td>营业收入</td><td>12,385</td><td>16,747</td><td>32,096</td><td>2025E 57,098</td><td>2026E 77,199</td></tr><tr><td>营业成本</td><td>(14,296)</td><td>(16,666)</td><td>(29,936)</td><td>(51,026)</td><td>(66,062)</td></tr><tr><td>毛利润(损失)</td><td>(1,911)</td><td>80</td><td>2,160</td><td>6,072</td><td>11,137</td></tr><tr><td>营业费用</td><td>(3,315)</td><td>(4,458)</td><td>(6,192)</td><td>(7,406)</td><td>(9,462)</td></tr><tr><td>销售、行政及一般费用</td><td>(1,114)</td><td>(1,795)</td><td>(2,264)</td><td>(2,794)</td><td>(3,601)</td></tr><tr><td>研发费用</td><td>(1,411)</td><td>(1,920)</td><td>(2,935)</td><td>(3,260)</td><td>(3,853)</td></tr><tr><td>其他支出</td><td>51</td><td>115</td><td>194</td><td>194</td><td>194</td></tr><tr><td>营业利润(损失)</td><td>(5,227)</td><td>(4,377)</td><td>(4,033)</td><td>(1,334)</td><td>1,676</td></tr><tr><td>营业外收支</td><td>118</td><td>161</td><td>286</td><td>179</td><td>196</td></tr><tr><td>利息收入/（支出）净额</td><td>106</td><td>157</td><td>267</td><td>145</td><td>145</td></tr><tr><td>衍生工具负债之公平值收益</td><td>12</td><td>4</td><td>17</td><td>17</td><td>18</td></tr><tr><td>其他收益-非经营</td><td></td><td></td><td>3</td><td>16</td><td>33</td></tr><tr><td>除税前溢利</td><td>(5,109)</td><td>(4,216)</td><td>(3,747)</td><td>(1,155)</td><td>1,872</td></tr><tr><td>所得税</td><td>(0)</td><td>(0)</td><td>0</td><td>1</td><td>1</td></tr><tr><td>净利润</td><td>(5,109)</td><td>(4,216)</td><td>(3,746)</td><td>(1,154)</td><td>1,873</td></tr><tr><td>基本股数(百万)</td><td>1,045</td><td>1,165</td><td>1,359</td><td>1,359</td><td>1,359</td></tr><tr><td>摊销股数(百万)</td><td>1,045</td><td>1,165</td><td>1,359</td><td>1,359</td><td>1,359</td></tr><tr><td>基本每股收益(元)</td><td>(4.89)</td><td>(3.62)</td><td>(2.76)</td><td>(0.85)</td><td>1.38</td></tr><tr><td>每股收益 (元)</td><td>(4.89)</td><td>(3.62)</td><td>(2.76)</td><td>(0.85)</td><td>1.38</td></tr></table></body></html>'`

ocr结果前面也是正确的
<img width="303" alt="企业微信截图_17326125947426" src="https://github.com/user-attachments/assets/d92b5698-5e65-42f9-b2b0-9ec1c47f57c0">

**Comment by Joker1212** [comment]
emmm,rapidTable主要是基于论文场景训练的，训练集是pubtabnet,基本都是小图片的简单表格，可能跟这个有关，另外试试二值化呢，不知道是不是颜色影响了，或者也可以试试我们另外一个库https://github.com/RapidAI/TableStructureRec?tab=readme-ov-file

**Comment by lyc728** [comment]
现在看到你们分享当中，这个表格模型精度应该是最高的把 我再试其他的也不合理了

**Comment by SWHL** [comment]
模型效果用单张图来看，不太合理哈。有些case就是会出错，说不上为啥。

**Comment by Joker1212** [comment]
这个其实可以在线试试就知道了，这就是rapidTable很典型的问题，它的识别框box，我刚刚试了读光的无线表格是可以的 
你可以先在线试试，选一下模型 https://www.modelscope.cn/studios/jockerK/TableRec
![image](https://github.com/user-attachments/assets/eb6f4309-c804-42bb-88db-fff8dfbf4078)
![image](https://github.com/user-attachments/assets/8fd32e36-1388-4eae-9dfa-bcfb078f36e6)

**Comment by lyc728** [comment]
你好 这个项目中的https://github.com/RapidAI/TableStructureRec 模型是没有的，是直接安装对应whl包吗？

**Comment by Joker1212** [comment]
嗯，直接安装包就行了，如果你只有无线表格，你也完全可以只安装无线表格识别的包

> 你好 这个项目中的https://github.com/RapidAI/TableStructureRec 模型是没有的，是直接安装对应whl包吗？
