### ISSUE TITLE
RapidTable输出的cell bboxes经常会比较错乱，没法定位回具体单元格，回溯要求高的场景使用较困难

### ISSUE THREAD

**Issue by enymfc25173** [RapidAI/RapidTable#29]
如题

**Comment by Joker1212** [comment]
emmm,两个办法，可以试试我们另外一个表格库，读光和unet模型的box要准一下，但是相比这个可能漏框，https://github.com/RapidAI/TableStructureRec, 另外可以尝试微调训练，参考paddleX https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/table_structure_recognition.md

**Comment by enymfc25173** [comment]
是不是还有个方式，获取匹配到的ocr box的坐标代替对应的单元格坐标？

**Comment by Joker1212** [comment]
ocr是行识别模型哈，有可能同个单元格中文字有换行，另外rapidTable的返回参数中，支持只返回表格识别结构，支持ocr_result和行列坐标和物理识别框的返回，你可以根据你的场景再匹配也是可以的
