### ISSUE TITLE
微调后的模型如何转onnx

### ISSUE THREAD

**Issue by drivingchangeworld** [RapidAI/RapidTable#36]
您好，请问一下 按照这个流程 https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/table_structure_recognition.md 微调slanet_plus模型后，如何导出onnx呢

**Comment by Joker1212** [comment]
直接使用paddle2onnx导出就可以了 https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by Joker1212** [comment]
> 您好，请问一下 按照这个流程 https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/ocr_modules/table_structure_recognition.md 微调slanet_plus模型后，如何导出onnx呢
直接使用paddle2onnx导出就可以了 https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by drivingchangeworld** [comment]
谢谢您的回复，我用paddle2onnx转onnx的过程中遇到了 ，Oops, there are some operators not supported yet, including sync_batch_norm,看起来是算子不支持，请问您遇到过这个问题么？

**Comment by Joker1212** [comment]
我之前遇到过，然后在issue给他们反馈过，你可以看看issue里面应该有提过这个表格模型转换的问题，包括paddle的版本都是一个兼容的

> 谢谢您的回复，我用paddle2onnx转onnx的过程中遇到了 ，Oops, there are some operators not supported yet, including sync_batch_norm,看起来是算子不支持，请问您遇到过这个问题么？

**Comment by drivingchangeworld** [comment]
好的，感谢感谢，我找一下相关的issue
